version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html
hooks:
  ApplicationStop:
    - location: code/stop.sh 
      runas: root
      timeout: 100
  BeforeInstall:
    - location: code/install.sh 
      runas: root
      timeout: 100
  AfterInstall:
    - location: code/copycode.sh 
      runas: root
      timeout: 100
  ApplicationStart:
    - location: code/start.sh 
      runas: root
      timeout: 100 
  ValidateService:
    - location: code/check.sh 
      runas: root
      timeout: 100